use serde::{Deserialize, Serialize};

use crate::{
    Snowflake,
    {
        presences::PresenceUpdate, stage_instances::StageInstance,
        welcomescreen_related::welcomescreens::WelcomeScreen,
    },
};

use super::{
    channel_related::channels::Channel, emojis::Emoji, features::Feature,
    guild_members::GuildMember,
    guild_scheduled_event_related::guild_scheduled_events::GuildScheduledEvent, roles::Role,
    stickers::Sticker, voice_states::VoiceState,
};

#[derive(Debug, Serialize, Deserialize)]
pub struct Guild {
    id: String,
    name: Option<String>,
    icon: Option<String>,
    icon_has: Option<String>,
    splash: Option<String>,
    discovery_splash: Option<String>,
    owner: Option<bool>,
    owner_id: Option<Snowflake>,
    permissions: Option<String>,
    region: Option<String>,
    afk_channel_id: Option<Snowflake>,
    afk_timeout: Option<i32>,
    widget_enabled: Option<bool>,
    widget_channel_id: Option<Snowflake>,
    verification_level: Option<i32>,
    default_message_notifications: Option<i32>,
    explicit_content_filter: Option<i32>,
    roles: Option<Vec<Role>>,
    emojis: Option<Vec<Emoji>>,
    features: Option<Vec<Feature>>,
    mfa_level: Option<i32>,
    application_id: Option<Snowflake>,
    system_channel_id: Option<Snowflake>,
    system_channel_flags: Option<i32>,
    rules_channel_id: Option<Snowflake>,
    joined_at: Option<String>,
    large: Option<bool>,
    unavailable: Option<bool>,
    member_count: Option<i32>,
    voice_states: Option<Vec<VoiceState>>,
    members: Option<Vec<GuildMember>>,
    channels: Option<Vec<Channel>>,
    threads: Option<Vec<Channel>>,
    presences: Option<Vec<PresenceUpdate>>,
    max_presences: Option<i32>,
    max_members: Option<i32>,
    vanity_url_code: Option<String>,
    description: Option<String>,
    banner: Option<String>,
    premium_tier: Option<i32>,
    premium_subscription_count: Option<i32>,
    preferred_locale: Option<String>,
    public_updates_channel_id: Option<Snowflake>,
    max_video_channel_users: Option<i32>,
    approximate_member_count: Option<i32>,
    approximate_presence_count: Option<i32>,
    welcome_screen: Option<WelcomeScreen>,
    nsfw_level: Option<i32>,
    stage_instances: Option<Vec<StageInstance>>,
    stickers: Option<Vec<Sticker>>,
    guild_scheduled_events: Option<Vec<GuildScheduledEvent>>,
    premium_progress_bar_enabled: Option<bool>,
}
